### AdaBoost vs Gradient Boosting vs XGBoost
Kaggle-Style Regression Project
Dataset Recommendation: House Prices - Advanced Regression Techniques (Kaggle)

Download: https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data

This notebook compares:

AdaBoost Regressor
Gradient Boosting Regressor
XGBoost Regressor
Evaluation Metrics:

RMSE
R² Score

In [1]:
#pip install xgboost

In [2]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

from xgboost import XGBRegressor

In [4]:
df=pd.read_csv('train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df = df.select_dtypes(include=['int64','float64'])

df = df.fillna(df.median())

print(df.shape)

(1460, 38)

In [7]:
y=df['SalePrice']
x=df.drop('SalePrice',axis=1)

print(x.shape)

(1460, 37)

In [8]:
# train test split

x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
def evaluate_model(model,name):
    model.fit(x_train,y_train)
    pred=model.predict(x_test)
    rmse=np.sqrt(mean_squared_error(y_test,pred))
    r2=r2_score(y_test,pred)

    print("="*50)
    print(name)
    print("RMSE:",round(rmse,2))
    print("R2 :",round(r2,4))

    return[name,rmse,r2]

In [16]:
ada=AdaBoostRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
ada_result = evaluate_model(ada, "ADABOOST")

==================================================
ADABOOST
RMSE: 36939.52
R2 : 0.8221

In [17]:
gb = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
gb_result=evaluate_model(gb,"GradientBoost")

==================================================
GradientBoost
RMSE: 28548.62
R2 : 0.8937

In [18]:
xgb = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
xgb_result=evaluate_model(xgb,"XGBoost")

==================================================
XGBoost
RMSE: 28647.01
R2 : 0.893

In [19]:
result=pd.DataFrame(
    [ada_result,gb_result,xgb_result],
    columns=['Model','RMSE','R2']
)

result.sort_values('RMSE')

           Model          RMSE        R2
1  GradientBoost  28548.616425  0.893743
2        XGBoost  28647.008081  0.893010
0       ADABOOST  36939.516626  0.822103