In [10]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor

from xgboost import XGBRegressor

In [11]:
df=pd.read_csv('Housing.csv')
print(df.shape)
df.head()

(545, 13)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [12]:
df = df.select_dtypes(include=['int64','float64'])

df = df.fillna(df.median())

print(df.shape)

(545, 6)

In [13]:
y=df['price']
x=df.drop('price',axis=1)

print(x.shape)

(545, 5)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
def evaluate_model(model, name):

    model.fit(x_train, y_train)

    pred = model.predict(x_test)

    rmse = np.sqrt(mean_squared_error(y_test, pred))

    r2 = r2_score(y_test, pred)

    print("="*50)
    print(name)
    print("RMSE :", round(rmse,2))
    print("R2   :", round(r2,4))

    return [name, rmse, r2]

In [16]:
ada = AdaBoostRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

ada_result = evaluate_model(ada, "AdaBoost")

==================================================
AdaBoost
RMSE : 1606678.0
R2   : 0.4893

In [17]:
gb = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb_result = evaluate_model(gb, "GradientBoost")

==================================================
GradientBoost
RMSE : 1548211.9
R2   : 0.5258

In [18]:
xgb = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

xgb_result = evaluate_model(xgb, "XGBoost")

==================================================
XGBoost
RMSE : 1531569.08
R2   : 0.5359

In [19]:
results = pd.DataFrame(
    [ada_result, gb_result, xgb_result],
    columns=['Model','RMSE','R2']
)

results.sort_values('RMSE')

           Model          RMSE        R2
2        XGBoost  1.531569e+06  0.535924
1  GradientBoost  1.548212e+06  0.525784
0       AdaBoost  1.606678e+06  0.489291